@php($copy=[
 'About'=>['eyebrow'=>'Who we are','title'=>'Saving lives. Planting hope. Building through faith.','text'=>'Established in February 2010, Kyagulanyi Ministries serves communities through safe water, education, health, livelihoods, leadership, and compassionate outreach.'],
 'Programs'=>['eyebrow'=>'Our programs','title'=>'Practical pathways to a stronger future.','text'=>'Explore clean water, community health, children and education, enterprise, and leadership initiatives.'],
 'Projects'=>['eyebrow'=>'Our projects','title'=>'See hope taking root in communities.','text'=>'Discover practical projects designed with local people and built for lasting impact.'],
 'Donate'=>['eyebrow'=>'Give with confidence','title'=>'Your generosity becomes hope in action.','text'=>'Support safe water, education, health, livelihoods, and community-led transformation.'],
 'Volunteer'=>['eyebrow'=>'Get involved','title'=>'Bring your time, skill, or partnership.','text'=>'There is meaningful work for every willing heart.'],
]);
@php($content=$copy[$page]??['eyebrow'=>'Kyagulanyi Ministries','title'=>$page,'text'=>'We are building stronger communities through practical service, local leadership, and hope.'])
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{$page}} · Kyagulanyi Ministries</title>@vite(['resources/css/app.css','resources/js/app.js'])</head><body><nav class="site-nav"><div class="nav-pill"><a class="brand-mark" href="/"><i class="bi bi-plus-square me-1"></i> Kyagulanyi</a><div class="nav-links"><a href="/about">About</a><a href="/programs">Programs</a><a href="/projects">Projects</a><a href="/news">News</a><a href="/volunteer">Volunteer</a></div><div class="nav-actions"><i class="bi bi-search"></i><span class="avatar">K</span><a class="nav-action" href="/donate"><i class="bi bi-heart"></i> Donate</a></div></div></nav><header class="page-hero"><div class="container"><p class="eyebrow text-light">{{$content['eyebrow']}}</p><h1>{{$content['title']}}</h1><p class="lead text-white-50 col-lg-7">{{$content['text']}}</p></div></header><main class="section-padding"><div class="container"><div class="row g-4"><div class="col-lg-8"><h2>{{$page}} that serve communities</h2><p class="lead">{{$content['text']}}</p><div class="row g-4 mt-2">@foreach(['Community-led solutions','Transparent stewardship','Hope that lasts'] as $item)<div class="col-md-4"><div class="card h-100"><i class="bi bi-check-circle icon-brand"></i><h5 class="mt-3">{{$item}}</h5><p>Working with local leaders and families to create measurable change.</p></div></div>@endforeach</div></div><div class="col-lg-4"><div class="card bg-light"><h4>Take the next step</h4><p>Join the work through giving, volunteering, or partnership.</p><a class="btn btn-brand" href="/donate">Get involved</a></div></div></div></div></main><footer class="site-footer"><div class="container d-flex justify-content-between flex-wrap gap-3"><span>© {{date('Y')}} Kyagulanyi Ministries</span><span>+256 701 234 567</span></div></footer></body></html>
