import { notFound } from 'next/navigation'; import Image from 'next/image'; import Link from 'next/link';
import { PageHero } from '@/components/ui/page-hero'; import { EngagementForm } from '@/components/forms/engagement-form'; import { news } from '@/lib/content'; import { getCollection } from '@/lib/strapi';

const content:Record<string,{eyebrow:string;title:string;text:string;image:string}>= {
 about:{eyebrow:'About Kyagulanyi Ministries',title:'Transforming lives, building communities, empowering the future.',text:'Established in February 2010, we are an indigenous Ugandan Christian non-profit serving rural villages through evangelism, clean water, education, health, and sustainable development.',image:'https://images.unsplash.com/photo-1520857014576-2c4f4c972b57?auto=format&fit=crop&w=2000&q=85'},
 events:{eyebrow:'Gather with us',title:'Come, connect, worship, and serve.',text:'Explore ministry gatherings, community outreaches, conferences, training, and volunteer opportunities.',image:'https://images.unsplash.com/photo-1507501336603-6e31db2be093?auto=format&fit=crop&w=2000&q=85'},
 news:{eyebrow:'Stories & news',title:'Witness hope taking root.',text:'Field updates, testimonies, ministry news, and honest stories from the communities we serve.',image:'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=2000&q=85'},
 media:{eyebrow:'Media',title:'Moments of faith, service, and community.',text:'Browse photographs, videos, audio messages, and resources from across the ministry.',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=2000&q=85'},
 volunteer:{eyebrow:'Volunteer',title:'Use what is in your hands to make a difference.',text:'Tell us about your skills, interests, and availability. We will help you find a meaningful place to serve.',image:'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=2000&q=85'},
 contact:{eyebrow:'Contact us',title:'We would love to hear from you.',text:'Reach our team about programs, partnerships, media, giving, visits, or general questions.',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=2000&q=85'},
 'prayer-request':{eyebrow:'Prayer',title:'You do not have to carry it alone.',text:'Share your prayer request confidentially with our pastoral care team. Public sharing is always optional.',image:'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=2000&q=85'},
 donate:{eyebrow:'Give with confidence',title:'Your generosity becomes hope in action.',text:'Choose a ministry priority or give where the need is greatest. Every contribution is stewarded with care and accountability.',image:'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=2000&q=85'},
 partners:{eyebrow:'Partnerships',title:'Greater impact happens together.',text:'Join churches, businesses, foundations, and community organizations investing in sustainable change.',image:'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=2000&q=85'},
 reports:{eyebrow:'Reports',title:'Accountability you can see.',text:'Access annual reports, impact updates, project reports, and financial accountability documents.',image:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=2000&q=85'},
 transparency:{eyebrow:'Transparency',title:'Trust is built through openness.',text:'Learn how we govern, safeguard people, steward resources, measure outcomes, and report our progress.',image:'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=2000&q=85'},
 campaigns:{eyebrow:'Campaigns',title:'Focused generosity. Visible progress.',text:'Support urgent and time-bound initiatives with clear goals, updates, and measurable outcomes.',image:'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=2000&q=85'},
 privacy:{eyebrow:'Legal',title:'Privacy policy',text:'How Kyagulanyi Ministries collects, uses, protects, and respects your personal information.',image:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=2000&q=85'},
 terms:{eyebrow:'Legal',title:'Terms of use',text:'The terms governing use of this website and its services.',image:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=2000&q=85'},
};
export function generateStaticParams(){return Object.keys(content).map(section=>({section}));}
export default async function SectionPage({params}:{params:Promise<{section:string}>}){const {section}=await params;const c=content[section];if(!c)notFound();const formType=section==='contact'?'contact':section==='volunteer'?'volunteer':section==='prayer-request'?'prayer-request':null;return <main><PageHero {...c}/>{formType?<section className="bg-[#f8f6f0] py-20"><div className="container-site grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Take the next step</p><h2 className="mt-3 font-serif text-4xl font-semibold text-[#071b33]">{section==='prayer-request'?'Our team is ready to pray.':section==='volunteer'?'Let’s find your place to serve.':'Start a conversation.'}</h2><p className="mt-5 text-sm leading-7 text-[#657184]">We treat every message with respect and respond during normal ministry office hours.</p></div><EngagementForm type={formType}/></div></section>:section==='donate'?<DonationContent/>:section==='about'?<AboutContent/>:<EditorialContent section={section}/>}</main>}
async function AboutContent(){const cmsTeam=await getCollection<Array<{slug:string;name:string;role:string;photo?:{url?:string}}>>('/team-members', []); const fallbackTeam=[['/pictures/unnamed (38).webp','Ministry Leadership','Leadership & partnerships'],['/pictures/unnamed (31).webp','Field Operations','Water and infrastructure'],['/pictures/unnamed (40).webp','Community Programmes','Education and care'],['/pictures/unnamed (43).webp','Mission Volunteers','Outreach and service']]; const teamEntries=cmsTeam.length?cmsTeam.map((member)=>{const fallback=fallbackTeam.find((item)=>item[1].toLowerCase().replaceAll(' ','-')===member.slug);return [member.photo?.url||fallback?.[0]||'/pictures/unnamed (38).webp',member.name,member.role] as [string,string,string];}):fallbackTeam; void teamEntries; return <>
  <section className="py-20 lg:py-28"><div className="container-site grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem]"><Image src="/pictures/unnamed (38).webp" alt="Kyagulanyi Ministries leadership and field team" fill className="object-cover" sizes="(max-width:1024px) 100vw, 45vw"/></div><div><p className="eyebrow">Our story</p><h2 className="mt-3 font-serif text-4xl font-semibold text-[#071b33]">Rooted in Uganda. Present in the places that need hope.</h2><div className="mt-6 space-y-5 text-[15px] leading-8 text-[#657184]"><p>Kyagulanyi Ministries was established in February 2010 as an indigenous Christian non-profit dedicated to evangelism, community health, clean water, education, and sustainable development.</p><p>From rural boreholes and church communities to children’s sponsorship and leadership training, our work is designed to help communities become self-sufficient and resilient.</p></div><div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="rounded-2xl bg-[#f8f6f0] p-5"><b className="font-serif text-3xl text-[#071b33]">2010</b><span className="mt-1 block text-xs font-bold text-[#657184]">Ministry established</span></div><div className="rounded-2xl bg-[#f8f6f0] p-5"><b className="font-serif text-3xl text-[#071b33]">Uganda</b><span className="mt-1 block text-xs font-bold text-[#657184]">Our mission field</span></div></div></div></div></section>
  <section className="bg-[#071b33] py-20 text-white lg:py-24"><div className="container-site grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow !text-[#e6bf71]">A word from our founder</p><h2 className="mt-3 font-serif text-4xl font-semibold">Service is faith made visible.</h2></div><blockquote className="border-l-2 border-[#d5a84b] pl-7 text-xl leading-9 text-white/80 sm:text-2xl">“We believe every human being, regardless of race, religion, location, or social and economic background, should have access to dignity, opportunity, and clean and safe drinking water. Our calling is to serve communities until they can stand strong for themselves.”<cite className="mt-5 block text-sm font-bold not-italic text-[#e6bf71]">— Founder, Kyagulanyi Ministries</cite></blockquote></div></section>
  <section className="relative overflow-hidden bg-[#2f76ad] py-20 text-white lg:py-28"><div className="absolute -top-16 left-1/2 h-40 w-40 -translate-x-1/2 rounded-full bg-[#d5a84b]/75"/><div className="absolute -bottom-24 -left-12 h-56 w-56 rounded-full border-[28px] border-white/5"/><div className="container-site relative"><div className="max-w-3xl"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#f2d994]">The people behind the work</p><h2 className="mt-3 font-serif text-5xl font-semibold leading-none sm:text-7xl">Our team</h2><p className="mt-6 max-w-2xl text-sm leading-7 text-white/75">Leaders, field practitioners, pastors, volunteers, and community partners working together across Uganda.</p></div><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{[
    [cmsTeam[0]?.photo?.url || '/pictures/unnamed (38).webp', cmsTeam[0]?.name || 'Ministry Leadership', cmsTeam[0]?.role || 'Leadership & partnerships'],
    [cmsTeam[1]?.photo?.url || '/pictures/unnamed (31).webp', cmsTeam[1]?.name || 'Field Operations', cmsTeam[1]?.role || 'Water and infrastructure'],
    [cmsTeam[2]?.photo?.url || '/pictures/unnamed (40).webp', cmsTeam[2]?.name || 'Community Programmes', cmsTeam[2]?.role || 'Education and care'],
    [cmsTeam[3]?.photo?.url || '/pictures/unnamed (43).webp', cmsTeam[3]?.name || 'Mission Volunteers', cmsTeam[3]?.role || 'Outreach and service'],
  ].map(([image,name,role])=><article key={name} className="group relative overflow-hidden rounded-3xl bg-[#171c22] pb-10"><div className="relative aspect-square overflow-hidden"><Image src={image} alt={name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:768px) 50vw, 25vw"/></div><div className="px-5 pb-8 pt-5"><h3 className="font-serif text-2xl font-semibold text-white">{name}</h3><p className="mt-2 text-sm font-bold uppercase tracking-[.12em] text-[#d5a84b]">{role}</p></div></article>)}</div></div></section>
  <section className="bg-[#f8f6f0] py-20"><div className="container-site grid gap-8 sm:grid-cols-3"><div><p className="eyebrow">Our commitment</p><h3 className="mt-2 font-serif text-2xl text-[#071b33]">Integrity</h3><p className="mt-2 text-sm leading-6 text-[#657184]">Clear reporting, documented stewardship, and responsible partnerships.</p></div><div><p className="eyebrow">Our approach</p><h3 className="mt-2 font-serif text-2xl text-[#071b33]">Community ownership</h3><p className="mt-2 text-sm leading-6 text-[#657184]">Solutions are built with local leaders and protected by the people they serve.</p></div><div><p className="eyebrow">Our hope</p><h3 className="mt-2 font-serif text-2xl text-[#071b33]">Sustainability</h3><p className="mt-2 text-sm leading-6 text-[#657184]">Every project should strengthen a community’s ability to thrive beyond our involvement.</p></div></div></section>
 </>}
function DonationContent(){return <section className="py-20"><div className="container-site grid gap-10 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow">Choose an amount</p><h2 className="mt-3 font-serif text-4xl text-[#071b33]">Make a secure gift</h2><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{['25,000','50,000','100,000','250,000'].map(x=><button key={x} className="rounded-2xl border border-slate-200 p-4 text-sm font-extrabold hover:border-[#d5a84b]">UGX {x}</button>)}</div><input placeholder="Other amount" className="mt-4 w-full rounded-2xl border border-slate-200 p-4"/><div className="mt-4 grid gap-3 sm:grid-cols-2"><button className="rounded-full bg-[#d5a84b] px-7 py-4 text-sm font-extrabold text-[#071b33]">Give once</button><button className="rounded-full border border-[#071b33] px-7 py-4 text-sm font-extrabold">Give monthly</button></div><p className="mt-5 text-xs leading-5 text-[#657184]">Payment processing will be activated when the ministry’s preferred provider and merchant credentials are supplied.</p></div><aside className="rounded-3xl bg-[#071b33] p-8 text-white"><p className="eyebrow !text-[#e6bf71]">Stewardship promise</p><h3 className="mt-3 font-serif text-3xl">Your trust matters.</h3><p className="mt-5 text-sm leading-7 text-white/65">We maintain clear controls, documented approvals, project tracking, and regular reporting so gifts are used responsibly and as designated.</p><Link href="/transparency" className="mt-6 inline-block text-sm font-bold text-[#e6bf71]">Read about accountability →</Link></aside></div></section>}
function EditorialContent({section}:{section:string}){return <section className="py-20"><div className="container-site"><div className="max-w-3xl"><p className="eyebrow">Our commitment</p><h2 className="mt-3 font-serif text-4xl font-semibold text-[#071b33]">People first. Christ at the center. Excellence in every detail.</h2><p className="mt-6 text-[15px] leading-8 text-[#657184]">We believe ministry is most faithful when it listens carefully, protects dignity, works transparently, and equips people to lead change in their own communities.</p></div><div className="mt-12 grid gap-6 md:grid-cols-3">{news.map((n,i)=><article key={n.title} className="overflow-hidden rounded-3xl border border-slate-200"><div className="relative aspect-[16/10]"><Image src={n.image} alt="" fill className="object-cover"/></div><div className="p-6"><p className="eyebrow">{section==='sermons'?'Message':section==='events'?'Upcoming':'Featured'}</p><h3 className="mt-3 font-serif text-2xl font-semibold text-[#071b33]">{section==='sermons'?['Living with courageous faith','Grace for the journey','A life poured out'][i]:section==='events'?['Community outreach day','Youth leadership gathering','Sunday celebration service'][i]:n.title}</h3><Link href="#" className="mt-5 inline-block text-xs font-extrabold text-[#8f6718]">Learn more →</Link></div></article>)}</div></div></section>}
