import Link from 'next/link';
import Image from 'next/image';
import { HiArrowLongRight, HiOutlineArrowRight, HiOutlineHeart, HiOutlinePlay, HiOutlineUserGroup } from 'react-icons/hi2';
import { Reveal } from '@/components/ui/reveal';
import { SectionHeading } from '@/components/ui/section-heading';
import { ImpactCounter } from '@/components/home/impact-counter';
import { news, programs, projects, stats } from '@/lib/content';

export default function Home() {
  return <main>
    <section className="relative min-h-[720px] overflow-hidden bg-[#071b33] text-white lg:min-h-[780px]">
      <Image src="https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=2000&q=90" alt="Community members walking together" fill priority className="block object-cover opacity-55 lg:hidden" sizes="100vw" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#06172b]/95 via-[#071b33]/65 to-transparent lg:hidden" />
      <div className="absolute inset-x-0 bottom-0 h-56 bg-gradient-to-t from-[#071b33] to-transparent lg:hidden" />
      <div className="container-site relative flex min-h-[720px] items-center py-24 lg:min-h-[780px]">
        <div className="relative z-10 hidden max-w-4xl lg:block"><p className="text-sm font-semibold uppercase tracking-[.35em] text-[#afd000]">Kyagulanyi Ministries</p><h1 className="mt-6 font-serif text-7xl font-semibold leading-[.95] text-white xl:text-[104px]">Saving lives.<br/><em className="font-normal text-[#afd000]">Planting hope.</em></h1><p className="mt-8 text-xl tracking-wide text-white/80">Building through faith.</p><div className="mt-10 h-px w-24 bg-[#afd000]"/></div>
        <Reveal className="max-w-3xl lg:hidden"><p className="mb-5 flex items-center gap-3 text-xs font-extrabold uppercase tracking-[.2em] text-[#f0ca7c]"><span className="h-px w-10 bg-[#d5a84b]"/> Serving rural Uganda since 2010</p><h1 className="display text-balance text-6xl font-semibold leading-[.96] sm:text-7xl lg:text-[92px]" style={{fontFamily:'var(--font-display)'}}>Transforming lives.<br/><em className="font-normal text-[#e2bd70]">Empowering the future.</em></h1><p className="mt-7 max-w-xl text-base leading-8 text-white/75 sm:text-lg">Through evangelism, clean water, education, community health, and sustainable economic development, we help communities move from survival to self-sufficiency.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/programs" className="focus-ring inline-flex items-center gap-3 rounded-full bg-[#d5a84b] px-7 py-4 text-sm font-extrabold text-[#071b33] transition hover:-translate-y-1 hover:bg-[#e5bd69]">Explore our work <HiArrowLongRight className="text-xl"/></Link><Link href="/about" className="focus-ring inline-flex items-center gap-3 rounded-full border border-white/30 bg-white/10 px-7 py-4 text-sm font-bold backdrop-blur-md hover:bg-white/20">Our story <HiOutlinePlay/></Link></div></Reveal>
      </div>
      <div className="absolute bottom-6 right-6 hidden rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur-xl"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/50">This month</p><p className="mt-1 font-serif text-xl">1,240 families reached</p></div>
    </section>

    <section className="bg-[#071b33] pb-16 text-white"><div className="container-site grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([v,l]) => <ImpactCounter key={l} value={v} label={l}/>)}</div></section>

    <section className="overflow-hidden py-24 lg:py-32"><div className="container-site grid items-center gap-14 lg:grid-cols-2 lg:gap-24">
      <Reveal className="relative"><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem]"><Image src="/pictures/unnamed (27).webp" alt="Kyagulanyi Ministries community gathering" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw"/></div><div className="animate-float absolute -bottom-7 -right-3 max-w-[220px] rounded-2xl bg-[#d5a84b] p-6 text-[#071b33] shadow-2xl sm:right-[-30px]"><HiOutlineHeart className="text-3xl"/><p className="mt-3 font-serif text-2xl font-semibold leading-tight">Every community carries God-given potential.</p></div></Reveal>
      <Reveal delay={.1}><SectionHeading eyebrow="Who we are" title="Transforming lives. Building communities. Empowering the future." text="Established in February 2010, Kyagulanyi Ministries is an indigenous Ugandan Christian non-profit serving rural communities across Uganda and East Africa."/><div className="mt-8 grid gap-6 sm:grid-cols-2"><div className="border-l-2 border-[#d5a84b] pl-5"><h3 className="font-serif text-2xl text-[#071b33]">Our mission</h3><p className="mt-2 text-sm leading-6 text-[#657184]">To render evangelism, community health programmes, clean water, education, and self-sustaining solutions that help communities end poverty.</p></div><div className="border-l-2 border-[#d5a84b] pl-5"><h3 className="font-serif text-2xl text-[#071b33]">Our vision</h3><p className="mt-2 text-sm leading-6 text-[#657184]">A Uganda where every person—regardless of background or location—can access dignity, opportunity, safe water, and hope.</p></div></div><Link href="/about" className="mt-9 inline-flex items-center gap-3 text-sm font-extrabold text-[#8f6718]">Discover our story <HiArrowLongRight className="text-xl"/></Link></Reveal>
    </div></section>

    <section className="bg-[#f8f6f0] py-24 lg:py-28"><div className="container-site"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="Our four pillars" title="Faith in action. Solutions that last." text="We pair the Gospel with practical, community-owned responses to Uganda’s most urgent needs."/><Link href="/programs" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#8f6718]">View all programmes <HiArrowLongRight className="text-xl"/></Link></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{programs.map((p,i)=><Reveal key={p.slug} delay={i*.06}><Link href={`/programs/${p.slug}`} className="group relative block aspect-[3/4] overflow-hidden rounded-3xl bg-[#071b33]"><Image src={p.image} alt="" fill className="object-cover opacity-65 transition duration-700 group-hover:scale-105" sizes="(max-width:768px) 100vw, 25vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#06172b] via-transparent to-transparent"/><span className="absolute left-5 top-5 grid h-10 w-10 place-items-center rounded-full border border-white/35 text-xs font-bold text-white">{p.icon}</span><div className="absolute inset-x-0 bottom-0 p-6 text-white"><h3 className="font-serif text-2xl font-semibold leading-tight">{p.title}</h3><p className="mt-3 line-clamp-2 text-xs leading-6 text-white/65">{p.text}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-[#e5c27d]">Learn more <HiOutlineArrowRight/></span></div></Link></Reveal>)}</div></div></section>

    <section className="py-24 lg:py-28"><div className="container-site"><SectionHeading eyebrow="Featured projects" title="See where hope is taking root." text="Transparent, measurable initiatives created with the people they serve."/><div className="mt-12 grid gap-7 lg:grid-cols-3">{projects.map((p,i)=><Reveal key={p.slug} delay={i*.08}><Link href={`/projects/${p.slug}`} className="group block overflow-hidden rounded-3xl border border-[#e6e2d9] bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[16/11] overflow-hidden"><Image src={p.image} alt="" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:1024px) 100vw, 33vw"/><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-wider text-[#071b33] backdrop-blur">{p.category}</span></div><div className="p-6"><p className="text-[11px] font-bold uppercase tracking-wider text-[#a47b2b]">{p.location}</p><h3 className="mt-2 font-serif text-2xl font-semibold leading-tight text-[#071b33]">{p.title}</h3><p className="mt-3 text-sm leading-6 text-[#657184]">{p.summary}</p><div className="mt-6"><div className="mb-2 flex justify-between text-xs font-bold"><span>{p.progress}% funded</span><span className="text-[#657184]">Goal UGX {(p.goal/1000000).toFixed(0)}M</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#d5a84b]" style={{width:`${p.progress}%`}}/></div></div></div></Link></Reveal>)}</div></div></section>

    <section className="grain bg-[#0b2948] py-24 text-white"><div className="container-site grid items-center gap-14 lg:grid-cols-[1.1fr_.9fr]"><Reveal><SectionHeading light eyebrow="Current campaign" title="Help build a place where every child can learn." text="Your gift helps complete classrooms, a safe water point, learning materials, and teacher support for the Bright Futures Learning Centre."/><div className="mt-8"><div className="flex items-end justify-between"><div><span className="text-xs text-white/50">Raised so far</span><strong className="mt-1 block font-serif text-3xl">UGX 61.2M</strong></div><strong className="font-serif text-3xl text-[#e4be70]">72%</strong></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-[#d5a84b]"/></div><p className="mt-3 text-xs text-white/50">Goal: UGX 85,000,000 · 38 days remaining</p></div><Link href="/donate" className="donate-cta mt-8 gap-3 px-7 py-4 text-sm">Donate now! <HiOutlineHeart className="text-lg"/></Link></Reveal><Reveal delay={.1} className="relative aspect-square overflow-hidden rounded-[2rem]"><Image src={projects[0].image} alt="Children learning" fill className="object-cover" sizes="(max-width:1024px) 100vw, 45vw"/></Reveal></div></section>

    <section className="py-24 lg:py-28"><div className="container-site"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="Stories & updates" title="The latest from the field."/><Link href="/news" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#8f6718]">All stories <HiArrowLongRight className="text-xl"/></Link></div><div className="mt-11 grid gap-8 lg:grid-cols-3">{news.map((n,i)=><Reveal key={n.title} delay={i*.08}><article className="group"><div className="relative aspect-[16/10] overflow-hidden rounded-2xl"><Image src={n.image} alt="" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:1024px) 100vw, 33vw"/></div><p className="mt-5 text-[10px] font-extrabold uppercase tracking-[.13em] text-[#a47b2b]">{n.category} · {n.date}</p><h3 className="mt-3 font-serif text-2xl font-semibold leading-tight text-[#071b33]">{n.title}</h3><Link href="/news" className="mt-4 inline-flex items-center gap-2 text-xs font-extrabold">Read story <HiOutlineArrowRight/></Link></article></Reveal>)}</div></div></section>

    <section className="bg-[#f0eadc] py-20"><Reveal className="container-site flex flex-col items-center justify-between gap-8 text-center lg:flex-row lg:text-left"><div className="flex max-w-2xl items-center gap-6"><span className="hidden h-16 w-16 shrink-0 place-items-center rounded-full bg-[#071b33] text-3xl text-[#d5a84b] sm:grid"><HiOutlineUserGroup/></span><div><p className="eyebrow">Your place in the story</p><h2 className="mt-2 font-serif text-4xl font-semibold text-[#071b33]">Bring your time, skill, or partnership.</h2><p className="mt-3 text-sm leading-6 text-[#657184]">There is meaningful work for every willing heart.</p></div></div><div className="flex flex-wrap justify-center gap-3"><Link href="/volunteer" className="rounded-full bg-[#071b33] px-7 py-4 text-sm font-extrabold !text-white transition hover:bg-[#0d2d4f]">Become a volunteer</Link><Link href="/partners" className="rounded-full border border-[#071b33]/20 px-7 py-4 text-sm font-extrabold text-[#071b33]">Partner with us</Link></div></Reveal></section>
  </main>;
}
