import Link from 'next/link';
import Image from 'next/image';
import { HiArrowLongRight, HiOutlineArrowRight, HiOutlineHeart, HiOutlineUserGroup } from 'react-icons/hi2';
import { Reveal } from '@/components/ui/reveal';
import { SectionHeading } from '@/components/ui/section-heading';
import { ImpactCounter } from '@/components/home/impact-counter';
import { news, programs, projects, stats } from '@/lib/content';
import heroImage from '../hero.jpg';

export default function Home() {
  return <main>
    <section className="relative min-h-[720px] overflow-hidden bg-[#071b33] text-white lg:min-h-[780px]">
      <Image src={heroImage} alt="Kyagulanyi Ministries serving communities" fill priority className="object-cover" sizes="100vw" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#075b3a]/90 via-[#075b3a]/55 to-transparent" />
      <div className="container-site relative flex min-h-[720px] items-center py-24 lg:min-h-[780px]">
        <Reveal className="relative z-10 max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.3em] text-[#afd000] sm:text-sm">Kyagulanyi Ministries</p><h1 className="mt-6 font-serif text-6xl font-semibold leading-[.95] text-white sm:text-7xl lg:text-[104px]">Saving lives.<br/><em className="font-normal text-[#afd000]">Planting hope.</em></h1><p className="mt-8 text-lg tracking-wide text-white/80 sm:text-xl">Building through faith.</p><div className="mt-10 h-px w-24 bg-[#afd000]"/></Reveal>
      </div>
      <div className="absolute bottom-6 right-6 hidden rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur-xl"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/50">This month</p><p className="mt-1 font-serif text-xl">1,240 families reached</p></div>
    </section>

    <section className="bg-[#071b33] pb-16 text-white"><div className="container-site grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([v,l]) => <ImpactCounter key={l} value={v} label={l}/>)}</div></section>

    <section className="overflow-hidden py-24 lg:py-32"><div className="container-site grid items-center gap-14 lg:grid-cols-2 lg:items-stretch lg:gap-24">
      <Reveal className="relative flex items-center justify-center"><div className="relative h-[320px] w-[320px] overflow-hidden rounded-full border-[18px] border-[#075b3a] shadow-xl sm:h-[390px] sm:w-[390px]"><Image src="/pictures/unnamed (27).webp" alt="Kyagulanyi Ministries community gathering" fill className="object-cover" sizes="(max-width: 1024px) 80vw, 390px"/></div><div className="absolute bottom-8 left-1/2 h-14 w-14 -translate-x-1/2 rotate-45 bg-[#075b3a] sm:bottom-5"/></Reveal>
      <Reveal delay={.1} className="flex flex-col justify-center"><p className="eyebrow">Who we are</p><h2 className="mt-3 font-serif text-5xl font-bold uppercase leading-tight text-[#075b3a]">Mission</h2><p className="mt-6 max-w-xl text-[15px] leading-8 text-[#5f6f66]">Established in February 2010, Kyagulanyi Ministries serves communities through safe water, education, health, livelihoods, leadership, and compassionate outreach. We help communities move from vulnerability to resilience through practical support, local leadership, and faith in action.</p><Link href="/about" className="mt-8 inline-flex items-center gap-3 text-sm font-extrabold text-[#075b3a]">Discover our story <HiArrowLongRight className="text-xl"/></Link></Reveal>
    </div></section>

    <section className="bg-[#f7f7f5] py-16 lg:py-20"><div className="container-site max-w-5xl"><div className="grid border border-[#dce8df] bg-white md:grid-cols-3"><div className="bg-[#3fad3c] px-6 py-5 text-center text-sm font-extrabold uppercase tracking-wide text-white">Purpose</div><div className="border-y border-[#dce8df] px-6 py-5 text-center text-sm font-extrabold uppercase tracking-wide text-[#075b3a] md:border-x md:border-y-0">Reach</div><div className="px-6 py-5 text-center text-sm font-extrabold uppercase tracking-wide text-[#075b3a]">Approach</div></div><div className="grid overflow-hidden bg-[#075b3a] text-white md:grid-cols-[.7fr_1.3fr]"><div className="relative min-h-[320px] md:min-h-[390px]"><Image src="/pictures/unnamed (16).webp" alt="Kyagulanyi Ministries community leader" fill className="object-cover"/></div><div className="flex flex-col justify-center p-8 sm:p-12"><p className="font-serif text-5xl italic text-[#c7e67a]">purpose</p><p className="mt-5 max-w-xl text-sm leading-7 text-white/85">Kyagulanyi Ministries exists to provide hope and practical resources that foster sustainable development. We serve vulnerable communities through safe water, education, health, livelihoods, leadership, and compassionate outreach—equipping local people to thrive.</p></div></div></div></section>

    <section className="bg-[#f8f6f0] py-24 lg:py-28"><div className="container-site"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="Our programs" title="Explore your place in the work." text="Choose a practical pathway to help communities thrive."/><Link href="/programs" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#075b3a]">View all programs <HiArrowLongRight className="text-xl"/></Link></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{programs.map((p,i)=><Reveal key={p.slug} delay={i*.06}><Link href={`/programs/${p.slug}`} className="group overflow-hidden border border-[#dce8df] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[16/10] overflow-hidden"><Image src={p.image} alt={p.title} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width:768px) 100vw, 25vw"/></div><div className="p-6"><h3 className="text-xl font-bold leading-tight text-[#171717]">{p.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#5f6f66]">{p.text}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#075b3a]">Explore program <HiOutlineArrowRight/></span></div></Link></Reveal>)}</div></div></section>

    <section className="py-24 lg:py-28"><div className="container-site"><SectionHeading eyebrow="Featured projects" title="See where hope is taking root." text="Transparent, measurable initiatives created with the people they serve."/><div className="mt-12 grid gap-7 lg:grid-cols-3">{projects.map((p,i)=><Reveal key={p.slug} delay={i*.08}><Link href={`/projects/${p.slug}`} className="group block overflow-hidden rounded-3xl border border-[#e6e2d9] bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[16/11] overflow-hidden"><Image src={p.image} alt="" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:1024px) 100vw, 33vw"/><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-wider text-[#071b33] backdrop-blur">{p.category}</span></div><div className="p-6"><p className="text-[11px] font-bold uppercase tracking-wider text-[#a47b2b]">{p.location}</p><h3 className="mt-2 font-serif text-2xl font-semibold leading-tight text-[#071b33]">{p.title}</h3><p className="mt-3 text-sm leading-6 text-[#657184]">{p.summary}</p><div className="mt-6"><div className="mb-2 flex justify-between text-xs font-bold"><span>{p.progress}% funded</span><span className="text-[#657184]">Goal UGX {(p.goal/1000000).toFixed(0)}M</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#d5a84b]" style={{width:`${p.progress}%`}}/></div></div></div></Link></Reveal>)}</div></div></section>

    <section className="grain bg-[#0b2948] py-24 text-white"><div className="container-site grid items-center gap-14 lg:grid-cols-[1.1fr_.9fr]"><Reveal><SectionHeading light eyebrow="Current campaign" title="Help build a place where every child can learn." text="Your gift helps complete classrooms, a safe water point, learning materials, and teacher support for the Bright Futures Learning Centre."/><div className="mt-8"><div className="flex items-end justify-between"><div><span className="text-xs text-white/50">Raised so far</span><strong className="mt-1 block font-serif text-3xl">UGX 61.2M</strong></div><strong className="font-serif text-3xl text-[#e4be70]">72%</strong></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-[#d5a84b]"/></div><p className="mt-3 text-xs text-white/50">Goal: UGX 85,000,000 · 38 days remaining</p></div><Link href="/donate" className="donate-cta mt-8 gap-3 px-7 py-4 text-sm">Donate now! <HiOutlineHeart className="text-lg"/></Link></Reveal><Reveal delay={.1} className="relative aspect-square overflow-hidden rounded-[2rem]"><Image src={projects[0].image} alt="Children learning" fill className="object-cover" sizes="(max-width:1024px) 100vw, 45vw"/></Reveal></div></section>

    <section className="py-24 lg:py-28"><div className="container-site"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="Stories & updates" title="The latest from the field."/><Link href="/news" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#8f6718]">All stories <HiArrowLongRight className="text-xl"/></Link></div><div className="mt-11 grid gap-8 lg:grid-cols-3">{news.map((n,i)=><Reveal key={n.title} delay={i*.08}><article className="group"><div className="relative aspect-[16/10] overflow-hidden rounded-2xl"><Image src={n.image} alt="" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:1024px) 100vw, 33vw"/></div><p className="mt-5 text-[10px] font-extrabold uppercase tracking-[.13em] text-[#a47b2b]">{n.category} · {n.date}</p><h3 className="mt-3 font-serif text-2xl font-semibold leading-tight text-[#071b33]">{n.title}</h3><Link href="/news" className="mt-4 inline-flex items-center gap-2 text-xs font-extrabold">Read story <HiOutlineArrowRight/></Link></article></Reveal>)}</div></div></section>

    <section className="bg-[#f0eadc] py-20"><Reveal className="container-site flex flex-col items-center justify-between gap-8 text-center lg:flex-row lg:text-left"><div className="flex max-w-2xl items-center gap-6"><span className="hidden h-16 w-16 shrink-0 place-items-center rounded-full bg-[#071b33] text-3xl text-[#d5a84b] sm:grid"><HiOutlineUserGroup/></span><div><p className="eyebrow">Your place in the story</p><h2 className="mt-2 font-serif text-4xl font-semibold text-[#071b33]">Bring your time, skill, or partnership.</h2><p className="mt-3 text-sm leading-6 text-[#657184]">There is meaningful work for every willing heart.</p></div></div><div className="flex flex-wrap justify-center gap-3"><Link href="/volunteer" className="rounded-full bg-[#071b33] px-7 py-4 text-sm font-extrabold !text-white transition hover:bg-[#0d2d4f]">Become a volunteer</Link><Link href="/partners" className="rounded-full border border-[#071b33]/20 px-7 py-4 text-sm font-extrabold text-[#071b33]">Partner with us</Link></div></Reveal></section>
  </main>;
}
