server {
    listen 80;
    server_name kyagulanyiministries.org www.kyagulanyiministries.org;

    client_max_body_size 50M;

    location /admin { proxy_pass http://127.0.0.1:1337; include proxy_params; }
    location /api { proxy_pass http://127.0.0.1:1337; include proxy_params; }
    location /uploads { proxy_pass http://127.0.0.1:1337; include proxy_params; expires 30d; }
    location / { proxy_pass http://127.0.0.1:3000; include proxy_params; }
}

